//** USER REDUX */
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//** CART REDUX */
export const TRIGGER_CART_MENU = "TRIGGER_CART_MENU";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const INCREASE_ITEM_QUANTITY = 'INCREASE_ITEM_QUANTITY';
export const DECREMENT_ITEM_QUANTITY = 'DECREMENT_ITEM_QUANTITY';